// CommonJS, every file is module (by default)
// Module - encapsulated code (only share minimum)

const names = require('./4-names')
const sayHi = require('./5-sayHi')
const data = require('./6-alternative-flavor')
require('./7-mind-grenade')
sayHi('Nadine')
sayHi(names.Jamal)
sayHi(names.Hadi)